## Sampling rate
#fs: 8000
#fs: 16000
#fs: 22050
fs: 24000
#fs: 44100
#fs: 48000

## Frame-shift mel-cep/mel-spec extraction
shiftms: 5
#shiftms: 10

## Window length mel-spectrogram extraction
winms: 27.5

## DC-component removal
highpass_cutoff: 65

## Mel-cepstrum
mcep_dim: 49

## Mel-spectrogram
mel_dim: 80

## Pre-emphasis noise-shaping coefficient
alpha: 0.85

## Coefficient for global variance (GV) postfilter
gv_coeff: 0.9

## GRU hidden units encoder, decoder spec, decoder excit
hidden_units_enc: 512
hidden_units_dec: 640
hidden_units_lf0: 128
hidden_units_post: 128

## GRU hidden units wavernn
#hidden_units_wave: 704 
hidden_units_wave: 736

hidden_units_wave_2: 32

## GRU hidden layers encoder, decoder spec, decoder excit
hidden_layers_enc: 1
hidden_layers_dec: 1
hidden_layers_lf0: 1
hidden_layers_post: 1

## GRU hidden layers wavernn
hidden_layers_wave: 1

## kernel-size input conv encoder
kernel_size_enc: 5
dilation_size_enc: 1

## kernel-size input conv decoder spec
kernel_size_dec: 5
dilation_size_dec: 1

## kernel-size input conv encoder excit
kernel_size_lf0: 7
dilation_size_lf0: 1

## kernel-size input conv post-net
kernel_size_post: 7
dilation_size_post: 1

## kernel-size input conv wavernn
kernel_size_wave: 7
dilation_size_wave: 1

## shallow WaveNet hyperparams.
kernel_size: 7
hid_chn: 256
skip_chn: 256
dilation_depth: 3
dilation_repeat: 2

## for using skewed input convolution (> 0), or balanced (0) [only for encoder]
#right_size_enc: 1
right_size_enc: 2
right_size_dec: 0
right_size_lf0: 0
## lookup frame limited to only 1/2 frame [for allowing low-latency/real-time processing]
#right_size_wave: 1
right_size_wave: 2
right_size_post: 0

## number of cycles :  n_half_cyc // 2
n_half_cyc: 2
#n_half_cyc: 4
## if cyclevae, use n_half_cyc:2, i.e., 1 cycle
## if cyclevqvae, use n_half_cyc:4, i.e., 2 cycles

## spect. latent dim.
lat_dim: 96

## excit. latent dim.
lat_dim_e: 32

## codebook size for cyclevqvae
ctr_size: 128

## use causal input convolution
## if using skewed input convolution for encoder (right_size > 0), set causal_conv dec/lf0 to true
## always use non-causal input conv. for encoder/wave
causal_conv_enc: false
causal_conv_dec: true
causal_conv_lf0: true
causal_conv_wave: false
causal_conv_post: true
## if right_size > 0 (skewed conv encoder, i.e., future frame is limited), set causal_conv dec/lf0 to true [low-latency/real-time proc.]

## use dim-reduction for cont. spk. embed from 1-hot code (only for cyclevae spec-excit)
spkidtr_dim: 0
#spkidtr_dim: 2
## to freely interpolate between 2-dim cont. spk-space

## learning rate
lr: 1e-4

## dropout rate
do_prob: 0.5

## maximum epoch count
#epoch_count: 110
#epoch_count: 120
#epoch_count: 125
epoch_count: 135
#epoch_count_wave: 35
#epoch_count_wave: 80
#epoch_count_wave: 360
epoch_count_wave: 487
## maximum epoch count

## use get_max_frame.sh to get max_frame of the current train/dev sets as the value of pad_len
## zero pad length [in frames] for batch processing; for neural vocoder, still use in frame length, but in computation it is multiplied by number of samples per frame
##arctic [bdl] 5 ms shift
#pad_len: 1207
##vctk [p252] 5 ms shift
#pad_len: 1955
##vcc18 [VCC2SM4,20026] 5 ms shift
#pad_len: 2149
##vcc20 [TMM1,M10036] 5 ms shift
pad_len: 2215

## Batch setting for spectral/excitation modeling
## 30 frames for 5 ms shift
batch_size: 30
## 15 frames for 10 ms shift
#batch_size: 15

## cyclevae vcc20+vctk(+vcc18+arctic)
#batch_size_utt: 80
## cyclevae vcc18+arctic
#batch_size_utt: 20
## cyclevae vcc18.vcc20, rule of thumb is to let each epoch at least has 100 distinct batches, 60 train. utterances x 14 speakers in vcc20 = 840 / 8 = 105 distinct batches per epoch
batch_size_utt: 8

## batch_size eval just follow the number of utterances in the corresponding dev. set or any number is ok
#batch_size_utt_eval: 10
batch_size_utt_eval: 14

## Batch setting for waveform modeling
## 30 frames x number of samples per frame, e.g., 30 x 120 for 24 kHz with 5 ms frame shift = 3600 batch smples
#batch_size_wave: 30
## 15 for 24 kHz with 10 ms shift --> 3600 samples
#batch_size_wave: 15
## 33 frames x number of samples per frame, e.g., 33 x 110 for 22.05 kHz with 5 ms frame shift = 3630 batch smples
#batch_size_wave: 33
## 17 for 22.05 kHz with 10 ms shift --> 3740 samples
#batch_size_wave: 17
## 45 for 16 kHz wavenet with 5 ms shift --> 3600 samples; rule of thumb is for wavenet use batch_size = 3600, and batch_size_utt = 2, regardless sampling rate and frame shift
#batch_size_wave: 45
## 23 for 16 kHz with 10 ms shift --> 3680 samples
#batch_size_wave: 23
## 8 for wavernn with 5 ms frame shift regardless of sampling rate
batch_size_wave: 8
## 4 for wavernn with 10 ms frame shift regardless of sampling rate
#batch_size_wave: 4

## wavenet, use batch_size (samples) equal to 3600 and batch_size_utt = 2, totaling 7200 samples in each optimization step
##          -> best value for wavenet modeling with more stability using 2 sequences per optim. step
#batch_size_utt_wave: 2
## wavernn --> use batch_size_utt = 8
batch_size_utt_wave: 8

## batch_size eval just follow the number of utterances in the corresponding dev. set or any number is ok
batch_size_utt_eval_wave: 14
#batch_size_utt_eval_wave: 16
#batch_size_utt_eval_wave: 42

# number of workers (threads) for batch data handling
n_workers: 2

mdl_name: cycmelspxlf0capspkvae-laplace

mdl_name_post: cycmelspxlf0capspkvae-post-smpl-laplace

##[8 kHz, 16 kHz, 22.05 kHz, 24 kHz]
mdl_name_wave: wavernn_dualgru_compact_lpc_mband_9bit
##[8 kHz, 16 kHz, 22.05 kHz, 24 kHz, 44.1 kHz, 48 kHz]
#mdl_name_wave: wavernn_dualgru_compact_lpc_mband_10bit_cf
##[8 kHz, 16 kHz, 22.05 kHz, 24 kHz]
#mdl_name_wave: wavernn_dualgru_compact_lpc_mband_16bit

## sparsification scheduling settings for wavernn
t_start: 20000
t_end: 1270000
interval: 20
densities: 0.09-0.09-0.12
n_stage: 4

## number of data-driven linear predictive coefficients (LPC) in wavernn
#lpc: 0
#lpc: 4
lpc: 6

### The frequency range per band must not be too narrow, otherwise the quality will be degraded.
### Optimum is at least 4 kHz per band.
##[8 kHz]
#n_bands: 2
##[16 kHz]
#n_bands: 4
##[22.05 kHz, 24 kHz]
n_bands: 5
##[44.1 kHz]
#n_bands: 10
##[48 kHz]
#n_bands: 12

#use_mcep: true
## mel-spectrogram-based modeling (wavernn)
use_mcep: false

## only if using mel-spectrogram, if set true, melsp+f0
with_excit: false
#with_excit: true
